version: r601-master-{build}

branches:
  only:
    - master

image: Visual Studio 2022

clone_depth: 1


platform:
  - x64

configuration:
  - Release

build:
  project: FlylinkDC_2022.sln
  verbosity: minimal
